version: '3'
services:

  database:
    image: postgres:latest
    restart: always
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: example
        POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - default
    volumes:
      - database_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    command: sh
    ports:
      - "8080:8080"
    expose:
      - 8080
    volumes:
        - .:/app
    links:
      - database
    depends_on:
      - database
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: example
        POSTGRES_DB: postgres
    networks:
      - default

networks:
  default:
    name: localdev

volumes:
  database_data:
    driver: local
