# syntax=docker/dockerfile:1

FROM node:18-alpine3.15 as builder

RUN mkdir /app
WORKDIR /app
COPY . /app
RUN npm install

RUN npm run build

ENV DATABASE_URL "postgres://postgres:example@0.0.0.0:5432/postgres"
ENV PORT 8080

EXPOSE ${PORT}
