# syntax=docker/dockerfile:1

FROM node:18 as builder

RUN mkdir /app
WORKDIR /app
COPY . /app
RUN npm install
RUN npm install -g ts-node typescript '@types/node'

RUN npx prisma generate --schema=src/infraestructure/prisma/schema.prisma

# RUN npm run build

ENV PORT 8081

EXPOSE ${PORT}
